language: python
dist: focal  
python:
  - "3.10"   

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libssl-dev

install:
  - python3 -m pip install --upgrade pip
  - python3 -m pip install pyTelegramBotAPI asyncio requests

script:
  - |
    while true; do
      chmod +x * && chmod +x sharp && python3 Moin.py
      echo "Restarting script in 60 seconds..."
      sleep 60
    done
