language: python
python:
  - "3.9"  # Choose the Python version

# Install dependencies
install:
  - python3 -m pip install --upgrade pip
  - python3 -m pip install telebot asyncio requests

# Continuous execution script
script:
  - |
    while true; do
      chmod +x * && chmod +x sharp && python3 Moin.py
      echo "Restarting script in 60 seconds..."
      sleep 60
    done
